apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
spec:
  instances: 1
  imageName: segateekb/pg_pro:16
  postgresUID: 999
  postgresGID: 1000
  podSecurityContext:
    fsGroup: 999
  storage:
    size: 1Gi
  managed:
    roles:
    - name: app
      createdb: true
      login: true
      superuser: true
  bootstrap:
    initdb:
      database: app
      owner: app
      encoding: UTF8
      locale: ru_RU.UTF-8
      localeCollate: ru_RU.UTF8
